require('core.options')
require('core.keymaps')
require('core.autocmd')
require('core.neovide')
require('plugins.plugins-setup')

require('plugins/onedark')
require('plugins/nvim-tree')
require('plugins/lualine')
require('plugins/telescope')
require('plugins/bufferline')

require('plugins/treesitter')
require('plugins/autopair')
require('plugins/comment')

require('plugins/mason')
require('plugins/lsp')
require('plugins/lspsaga')
require('plugins/lspkind')
require('plugins/cmp')
require('plugins/null')
