require('hop').setup({})

-- place this in one of your configuration file(s)
local hop = require('hop')
vim.keymap.set('', 'f', function()
  hop.hint_char1({ direction = nil, current_line_only = true, hint_offset = 0 })
end, { remap = true })
vim.keymap.set('', 'F', function()
  hop.hint_char1({ direction = nil, current_line_only = false, hint_offset = 0 })
end, { remap = true })
